services:
  mysql:
    image: mariadb:10.5.10
    container_name: aodata-mysql
    restart: on-failure
    environment:
      MARIADB_ROOT_PASSWORD: ${MYSQL_PWD}
    ports:
      - 3306:3306
    volumes:
      - ./mysqldata:/var/lib/mysql
      - ./mysqlbackup:/mysqlbackup
    networks:
      - albiondata
  web:
    image: ruby:3
    build:
      context: .
    platform: linux/amd64
    container_name: web
    restart: on-failure
    volumes:
      - ./:/rails
    environment:
      RAILS_ENV: development
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PWD: ${MYSQL_PWD}
      MYSQL_DB: ${MYSQL_DB}
      MYSQL_PORT: ${MYSQL_PORT:-3306}
      MYSQL_EXPORT_PATH: ${MYSQL_EXPORT_PATH}
      NATS_HOST: ${NATS_HOST}
      NATS_PORT: ${NATS_PORT}
      NATS_USER: ${NATS_USER}
      NATS_PWD: ${NATS_PWD}
      NATS_SEND_DISABLE: ${NATS_SEND_DISABLE}
      SIDEKIQ_REDIS_HOST: ${SIDEKIQ_REDIS_HOST}
      SIDEKIQ_REDIS_PORT: ${SIDEKIQ_REDIS_PORT}
      SIDEKIQ_REDIS_DB: ${SIDEKIQ_REDIS_DB}
      SIDEKIQ_THREADS: 10
      SIDEKIQ_WEB_USER: ${SIDEKIQ_WEB_USER}
      SIDEKIQ_WEB_PASS: ${SIDEKIQ_WEB_PASS}
      SECRET_KEY_BASE: ${SECRET_KEY_BASE}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      REDIS_DB: ${REDIS_DB}
      ABUSEIPDB_REDIS_URL: ${ABUSEIPDB_REDIS_URL}
      ABUSEIPDB_API_KEY: ${ABUSEIPDB_API_KEY}
    # command: './entrypoint.sh web'
    entrypoint: ./entrypoint.sh sleep
    ports:
      - 3000:3000
    depends_on:
      - redis
      - mysql
    networks:
      - albiondata
    logging:
      options:
        tag: "{{.ImageName}}/{{.Name}}/{{.ID}}"
  # sidekiq:
  #   image: ruby:3
  #   build:
  #     context: .
  #   platform: linux/amd64
  #   container_name: sidekiq
  #   restart: on-failure
  #   volumes:
  #     - ./:/usr/src/app
  #   environment:
  #     MYSQL_USER: ${MYSQL_USER}
  #     MYSQL_PWD: ${MYSQL_PWD}
  #     MYSQL_DB: ${MYSQL_DB}
  #     MYSQL_EXPORT_PATH: ${MYSQL_EXPORT_PATH}
  #     SIDEKIQ_REDIS_HOST: ${SIDEKIQ_REDIS_HOST}
  #     SIDEKIQ_REDIS_PORT: ${SIDEKIQ_REDIS_PORT}
  #     SIDEKIQ_REDIS_DB: ${SIDEKIQ_REDIS_DB}
  #     SIDEKIQ_THREADS: 1
  #     SIDEKIQ_WEB_USER: ${SIDEKIQ_WEB_USER}
  #     SIDEKIQ_WEB_PASS: ${SIDEKIQ_WEB_PASS}
  #   command: './entrypoint.sh sidekiq'
  #   depends_on:
  #     - redis
  #   networks:
  #     - albiondata
  #   logging:
  #     options:
  #       tag: "{{.ImageName}}/{{.Name}}/{{.ID}}"
  # sleep:
  #   image: ruby:3
  #   build:
  #     context: .
  #   platform: linux/amd64
  #   container_name: sleep
  #   restart: on-failure
  #   volumes:
  #     - ./:/usr/src/app
  #   environment:
  #     MYSQL_USER: ${MYSQL_USER}
  #     MYSQL_PWD: ${MYSQL_PWD}
  #     MYSQL_DB: ${MYSQL_DB}
  #     MYSQL_EXPORT_PATH: ${MYSQL_EXPORT_PATH}
  #     SIDEKIQ_REDIS_HOST: ${SIDEKIQ_REDIS_HOST}
  #     SIDEKIQ_REDIS_PORT: ${SIDEKIQ_REDIS_PORT}
  #     SIDEKIQ_REDIS_DB: ${SIDEKIQ_REDIS_DB}
  #     SIDEKIQ_THREADS: 1
  #     SIDEKIQ_WEB_USER: ${SIDEKIQ_WEB_USER}
  #     SIDEKIQ_WEB_PASS: ${SIDEKIQ_WEB_PASS}
  #   command: './entrypoint.sh sleep'
  #   depends_on:
  #     - redis
  #   networks:
  #     - albiondata
  #   logging:
  #     options:
  #       tag: "{{.ImageName}}/{{.Name}}/{{.ID}}"
  redis:
    image: redis
    container_name: redis
    restart: on-failure
    ports:
      - 6379:6379
    volumes:
      - ./redisdata:/data
    command: redis-server --appendonly yes
    networks:
      - albiondata
networks:
  albiondata:
