services:
  mysql:
    image: mariadb:10.5.10
    container_name: aodata-mysql
    restart: on-failure
    environment:
      MARIADB_ROOT_PASSWORD: ${MYSQL_ROOT_PWD}
    ports:
      - 3306:3306
    volumes:
      - ./mysqldata:/var/lib/mysql
      - ./mysqlbackup:/mysqlbackup
    networks:
      - albiondata
  web:
    image: ruby:3
    build:
      context: .
    platform: linux/amd64
    container_name: web
    restart: on-failure
    volumes:
      - ./:/rails
    environment:
      RAILS_ENV: development
      MYSQL_WEST_URL: ${MYSQL_WEST_URL}
      MYSQL_EAST_URL: ${MYSQL_EAST_URL}
      MYSQL_EUROPE_URL: ${MYSQL_EUROPE_URL}
      MYSQL_EXPORT_PATH: ${MYSQL_EXPORT_PATH}
      NATS_WEST_URL: ${NATS_WEST_URL}
      NATS_EAST_URL: ${NATS_EAST_URL}
      NATS_EUROPE_URL: ${NATS_EUROPE_URL}
      NATS_SEND_DISABLE: ${NATS_SEND_DISABLE}
      SIDEKIQ_REDIS_URL: ${SIDEKIQ_REDIS_URL}
      SIDEKIQ_THREADS: 10
      SIDEKIQ_WEB_USER: ${SIDEKIQ_WEB_USER}
      SIDEKIQ_WEB_PASS: ${SIDEKIQ_WEB_PASS}
      SECRET_KEY_BASE: ${SECRET_KEY_BASE}
      REDIS_WEST_URL: ${REDIS_WEST_URL}
      REDIS_EAST_URL: ${REDIS_EAST_URL}
      REDIS_EUROPE_URL: ${REDIS_EUROPE_URL}
      ABUSEIPDB_REDIS_URL: ${ABUSEIPDB_REDIS_URL}
      ABUSEIPDB_API_KEY: ${ABUSEIPDB_API_KEY}
      RACKATTACK_REDIS_URL: ${RACKATTACK_REDIS_URL:-redis://redis:6379/9}
      THROTTLE_API_1MIN: ${THROTTLE_API_1MIN}
      THROTTLE_API_5MIN: ${THROTTLE_API_5MIN}
      THROTTLE_POW_1MIN: ${THROTTLE_POW_1MIN}
      THROTTLE_POW_1HOUR: ${THROTTLE_POW_1HOUR}
      THROTTLE_POW_1DAY: ${THROTTLE_POW_1DAY}
    # command: './entrypoint.sh web'
    entrypoint: ./entrypoint.sh sleep
    ports:
      - 3000:3000
    depends_on:
      - redis
      - mysql
    networks:
      - albiondata
    logging:
      options:
        tag: "{{.ImageName}}/{{.Name}}/{{.ID}}"
  redis:
    image: redis
    container_name: redis
    restart: on-failure
    ports:
      - 6379:6379
    volumes:
      - ./redisdata:/data
    command: redis-server --appendonly yes
    networks:
      - albiondata
networks:
  albiondata:
