# SQLite. Versions 3.8.0 and up are supported.
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem "sqlite3"
#
default: &default
  # adapter: mysql2
  adapter: trilogy
  host: <%= ENV['MYSQL_HOST'] %>
  username: <%= ENV['MYSQL_USER'] %>
  password: <%= ENV['MYSQL_PWD'] %>
  database: <%= ENV['MYSQL_DB'] %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  encoding: utf8
  # socket: /tmp/mysql.sock

development:
  <<: *default

test:
  <<: *default
  database: test

production:
  <<: *default
