# SQLite. Versions 3.8.0 and up are supported.
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem "sqlite3"
#
default: &default
  adapter: trilogy
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  encoding: utf8
  url: <%= ENV['MYSQL_WEST_URL'] %>
  multidb:
    fallback: true
    databases:
      west:
        url: <%= ENV['MYSQL_WEST_URL'] %>
      east:
        url: <%= ENV['MYSQL_EAST_URL'] %>
      europe:
        url: <%= ENV['MYSQL_EUROPE_URL'] %>

development:
  <<: *default

test:
  <<: *default
  url: <%= ENV['MYSQL_WEST_URL'] %>_test
  multidb:
    databases:
      west:
        url: <%= ENV['MYSQL_WEST_URL'] %>_test
      east:
        url: <%= ENV['MYSQL_EAST_URL'] %>_test
      europe:
        url: <%= ENV['MYSQL_EUROPE_URL'] %>_test

production:
  <<: *default
